---
openapi: 3.0.1
info:
  title: Episode Six API
  license:
    name: Copyright ® EPISODE SIX
  version: v2.0
externalDocs:
  description: Privacy Policy
  url: https://episodesix.com/privacy-policy/
security:
  - BearerAuth: [] # Refer to the name defined in securitySchemes
paths:
  "/v1/customers/{customer-id}/activity":
    get:
      tags:
      - Account Activity
      summary: Retrieve Customer Account Activity
      description: |-
        Provides the most recent activity from the API log that corresponds to this customer.
        Roles Allowed: CustomerAgent, CustomerManager, RiskManager, RiskAgent
      operationId: net.e6tech.h3.middletier.api.v1.partner.customer.CustomerAPI_getRecentActivity_GET
      parameters:
      - name: customer-id
        in: path
        description: An encrypted identifier for a Customer for an instance obtained
          from a Tritium API.
        required: true
        schema:
          type: string
        example: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RecentActivityPaginationDTO"
components:
  schemas:
    RecentActivityDTO:
      type: object
      properties:
        creationTime:
          type: integer
          description: Timestamp expressed in UNIX epoch time.
          format: int64
          example: 1685382882256
          readOnly: true
        modifiedTime:
          type: integer
          description: Timestamp expressed in UNIX epoch time.
          format: int64
          example: 1685382882256
          readOnly: true
        id:
          type: string
          description: An encrypted identifier for this instance generated by Tritium.
          example: 4A5A0CCEA6CC7089E77631346031F593-1000001014
          readOnly: true
        type:
          type: string
          description: Activity type that describes this entry.
          example: CUSTOMER_BLOCK_CREATED
          enum:
          - CUSTOMER_BLOCK_CREATED
          - CARD_BLOCK_CREATED
          - CUSTOMER_BLOCK_RELEASED
          - CUSTOMER_BLOCK_RELEASED_WITH_MEMO
          - CARD_BLOCK_RELEASED
          - CARD_BLOCK_RELEASED_WITH_MEMO
          - CARD_ORDERED
          - CUSTOMER_MEMO_CREATED
          - CHANGE_ORDER_CREATED
          - CHANGE_ORDER_APPROVED
      description: The retrieved objects. The data structure depends on the query
        executed.
    RecentActivityPaginationDTO:
      required:
      - count
      - data
      - endIndex
      - lastPage
      - startIndex
      - totalCount
      type: object
      properties:
        count:
          type: integer
          description: The number of return objects.
          format: int32
          example: 1
        startIndex:
          type: integer
          description: The starting index of the objects.
          format: int32
          example: 0
        endIndex:
          type: integer
          description: The ending index of the objects. It is equal to the starting
            index plus count.
          format: int32
          example: 1
        lastPage:
          type: boolean
          description: Is last page flag.
          example: false
        totalCount:
          type: integer
          description: Total number of records available.  However, PaginationDTO
            only includes data ranging from the starting index to ending index - 1.
          format: int32
          example: 1
        data:
          type: array
          description: The retrieved objects. The data structure depends on the query
            executed.
          items:
            "$ref": "#/components/schemas/RecentActivityDTO"
  securitySchemes:
    BearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer