---
openapi: 3.0.1
info:
  title: Episode Six API
  license:
    name: Copyright ® EPISODE SIX
  version: v2.0
externalDocs:
  description: Privacy Policy
  url: https://episodesix.com/privacy-policy/
security:
  - BearerAuth: [] # Refer to the name defined in securitySchemes
paths:
  "/v1/programs":
    post:
      tags:
      - Programs
      summary: Create Program
      description: |-
        Creates a program and configures its basic foundational information.
        Roles Allowed: PlatformManager
      operationId: net.e6tech.h3.middletier.api.v1.partner.operating.OperatingAPI_create_POST
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateOperatingProgramDTO"
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/OperatingProgramDTO"
    get:
      tags:
      - Programs
      summary: List Programs
      description: |-
        Lists operating programs with details on each operating program currently configured in the system.
        Roles Allowed: Approver, PlatformManager, ProgramManager, RetailManager, RiskManager, RiskAgent, CustomerManager, CustomerAgent, FinancialManager
      operationId: net.e6tech.h3.middletier.api.v1.partner.operating.OperatingAPI_list_GET
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/OperatingProgramDTO"
  "/v1/programs/{program-name}":
    get:
      tags:
      - Programs
      summary: Retrieve Program
      description: |-
        Retrieves a program identified by its `program-name`.
        Roles Allowed: Approver, PlatformManager, ProgramManager, RetailManager, RiskManager, RiskAgent, CustomerManager, CustomerAgent, FinancialManager
      operationId: net.e6tech.h3.middletier.api.v1.partner.operating.OperatingAPI_get_GET
      parameters:
      - name: program-name
        in: path
        description: A unique identifier for a Program provided on program creation
        required: true
        schema:
          type: string
        example: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/OperatingProgramDTO"
    post:
      tags:
      - Programs
      summary: Update Program
      description: |-
        Update the operating program language and/or custodialTimezone.

        Roles Allowed: ProgramManager, FinancialManager
      operationId: net.e6tech.h3.middletier.api.v1.partner.operating.OperatingAPI_updateOperatingProgram_POST
      parameters:
      - name: program-name
        in: path
        description: A unique identifier for a Program provided on program creation
        required: true
        schema:
          type: string
        example: ''
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateOperatingProgramDTO"
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json: {}
components:
  schemas:
    UpdateOperatingProgramDTO:
      type: object
      properties:
        timeZone:
          type: string
          description: New timezone to set in the program
          example: Australia/Sydney
        language:
          type: string
          description: New language of the operating program
          example: en-US
    OperatingProgramDTO:
      required:
      - bankname
      - currencies
      - defaultHomeCurrency
      - language
      - name
      - partnerName
      type: object
      properties:
        creationTime:
          type: integer
          description: 'Timestamp expressed in unix epoch time. '
          format: int64
          readOnly: true
          example: 1547573554173
        modifiedTime:
          type: integer
          description: 'Timestamp expressed in unix epoch time. '
          format: int64
          readOnly: true
          example: 1547573554173
        id:
          type: string
          description: An encrypted identifier for this instance generated by Tritium
          readOnly: true
          example: 8202C315D8960020534E4D9E0C5509BE-1000057006
        name:
          type: string
          description: Name of the operating program.
          example: example_program_name
        defaultHomeCurrency:
          type: string
          description: ISO currency code for the default home currency.
          example: USD
        currencies:
          type: array
          description: ISO currency code supported by the program.
          example:
          - USD
          - AUD
          - GBP
          items:
            type: string
            description: ISO currency code supported by the program.
            example: USD
        language:
          type: string
          description: Primary language of the operating program.
          example: en-US
        bankName:
          type: string
          description: Name of the bank associated with the operating program.
          example: mock_bank
        partnerName:
          type: string
          description: Name of the partner associated with the operating program.
          example: mock_partner
        timeZone:
          type: string
          description: The timeZone associated with the operating program.
          example: America/Chicago
    CreateOperatingProgramDTO:
      type: object
      properties:
        creationTime:
          type: integer
          description: 'Timestamp expressed in unix epoch time. '
          format: int64
          readOnly: true
          example: 1547573554173
        modifiedTime:
          type: integer
          description: 'Timestamp expressed in unix epoch time. '
          format: int64
          readOnly: true
          example: 1547573554173
        id:
          type: string
          description: An encrypted identifier for this instance generated by Tritium
          readOnly: true
          example: 8202C315D8960020534E4D9E0C5509BE-1000057006
        name:
          type: string
          description: Name of the operating program.
          example: example_program_name
        defaultHomeCurrency:
          type: string
          description: ISO currency code for the default home currency.
          example: USD
        currencies:
          type: array
          description: ISO currency code supported by the program.
          example:
          - USD
          - AUD
          - GBP
          items:
            type: string
            description: ISO currency code supported by the program.
            example: USD
        language:
          type: string
          description: Primary language of the operating program.
          example: en-US
        bankName:
          type: string
          description: Name of the bank associated with the operating program.
          example: mock_bank
        partnerName:
          type: string
          description: Name of the partner associated with the operating program.
          example: mock_partner
        timeZone:
          type: string
          description: Time zone for the partner. Used for settlement.
          example: America/Chicago
        country:
          type: string
          description: ISO country code
          example: US
        tPlusDay:
          type: integer
          description: Time difference between transaction and settlement in day(s).
            This field is added to `tPlusHour` and `tPlusMinute` to reflect total
            time.
          format: int32
          example: 1
        tPlusHour:
          type: integer
          description: Time difference between transaction and settlement in hour(s).
          format: int32
          example: 0
        tPlusMinute:
          type: integer
          description: Time difference between transaction and settlement in minute(s).
          format: int32
          example: 0
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer